package ${package}.server.bindery.generator;

import java.io.IOException;
import java.io.Writer;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.Elements;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;

import com.google.inject.Module;
import ${package}.server.AppServletContextListener;
import ${package}.server.bindery.AutoLoadModule;

@SupportedSourceVersion(value = SourceVersion.RELEASE_8)
public class ModuleMavenProcesser extends AbstractProcessor {
	private Filer mFiler;
	private Messager mMessager;
	private Elements mElementUtils;
	
	@Override
	public Set<String> getSupportedAnnotationTypes() {
		Set<String> annotations = new LinkedHashSet<>();
        annotations.add(AutoLoadModule.class.getCanonicalName());
        return annotations;
	}
	
	@Override
	public void init(ProcessingEnvironment processingEnv) {
		super.init(processingEnv);
		mFiler = processingEnv.getFiler();
		mMessager = processingEnv.getMessager();
		mElementUtils = processingEnv.getElementUtils();
	}

	@Override
	public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
		Set<? extends Element> bindViewElements = roundEnv.getElementsAnnotatedWith(AutoLoadModule.class);
		
		if(bindViewElements.size() == 0)
			return false;

        try {
            JavaFileObject jfo = mFiler.createSourceFile("${package}.server.MavenProcessedServletContextListener", new Element[]{});
            Writer writer = jfo.openWriter();
	        StringBuilder builder = new StringBuilder();
	        builder.append("package ${package}.server" + ";\n\n");
	        builder.append("import " + List.class.getCanonicalName() + ";\n");
	        builder.append("import " + Module.class.getCanonicalName() + ";\n\n");

	        builder.append("//Auto generated by apt,do not modify!!\n\n");

	        builder.append("public class MavenProcessedServletContextListener extends " + AppServletContextListener.class.getName() + " { \n\n");
	        builder.append("  @Override\r\n  public void appendModules(List<Module> list) {\r\n");

	        for (Element element : bindViewElements) {
	            PackageElement packageElement = mElementUtils.getPackageOf(element);
	    		note("Process: " + packageElement.getQualifiedName() + "." + element.getSimpleName());
		        builder.append("    list.add(new " + packageElement.getQualifiedName() + "." + element.getSimpleName() + "());\n");
	        	
	        }

	        builder.append("  }\n");
	        builder.append("}");

	        writer.write(builder.toString());
            writer.flush();
            writer.close();
        } catch (IOException e) {
        	note("Processer Exception:" + e);
            e.printStackTrace();
        }
        return true;
	}

	 private void note(String msg) {
	        mMessager.printMessage(Diagnostic.Kind.NOTE, msg);
    }
}
